//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using Bright.Serialization;
using System.Collections.Generic;
using SimpleJSON;



namespace cfg
{ 

public sealed partial class TbTextMapper
{
    private readonly Dictionary<string, MapperItem> _dataMap;
    private readonly List<MapperItem> _dataList;
    
    public TbTextMapper(JSONNode _json)
    {
        _dataMap = new Dictionary<string, MapperItem>();
        _dataList = new List<MapperItem>();
        
        foreach(JSONNode _row in _json.Children)
        {
            var _v = MapperItem.DeserializeMapperItem(_row);
            _dataList.Add(_v);
            _dataMap.Add(_v.Key, _v);
        }
        PostInit();
    }

    public Dictionary<string, MapperItem> DataMap => _dataMap;
    public List<MapperItem> DataList => _dataList;

    public MapperItem GetOrDefault(string key) => _dataMap.TryGetValue(key, out var v) ? v : null;
    public MapperItem Get(string key) => _dataMap[key];
    public MapperItem this[string key] => _dataMap[key];

    public void Resolve(Dictionary<string, object> _tables)
    {
        foreach(var v in _dataList)
        {
            v.Resolve(_tables);
        }
        PostResolve();
    }

    public void TranslateText(System.Func<string, string, string> translator)
    {
        foreach(var v in _dataList)
        {
            v.TranslateText(translator);
        }
    }
    
    
    partial void PostInit();
    partial void PostResolve();
}

}