//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using Bright.Serialization;
using SimpleJSON;


namespace cfg
{ 
   
public sealed partial class Tables
{
    public TbTextMapper TbTextMapper {get; }

    public Tables(System.Func<string, JSONNode> loader)
    {
        var tables = new System.Collections.Generic.Dictionary<string, object>();
        TbTextMapper = new TbTextMapper(loader("tbtextmapper")); 
        tables.Add("TbTextMapper", TbTextMapper);
        PostInit();

        TbTextMapper.Resolve(tables); 
        PostResolve();
    }

    public void TranslateText(System.Func<string, string, string> translator)
    {
        TbTextMapper.TranslateText(translator); 
    }
    
    partial void PostInit();
    partial void PostResolve();
}

}